
server:
 port: 8000
 servlet:
    encoding:
      charset: UTF-8
      

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: unishop
    password: korea1234
    url: jdbc:mysql://localhost:3306/unishopdb      
    
    
  jpa:
    hibernate:
      ddl-auto: none #create:, update, none
    show-sql: true
